FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04
RUN apt-get update && apt-get install -y python3-pip && rm -rf /var/lib/apt/lists/*
RUN pip3 install --no-cache-dir torch --extra-index-url https://download.pytorch.org/whl/cu121
RUN pip3 install --no-cache-dir transformers==4.33.0
RUN pip3 install --no-cache-dir TTS fastapi uvicorn
ENV HF_HOME=/root/.cache/huggingface
WORKDIR /app
COPY server.py .
COPY sem-título.wav .
EXPOSE 8020
CMD ["uvicorn","server:app","--host","0.0.0.0","--port","8020"]
